/**
 * @file Module containing functions relating to the cheerleader functionality of the app. The purpose of cheerleader is to give the user feedback encouraging them after completing tasks.
 * @module Cheerleader
 */

import { ToastAndroid } from 'react-native';
const responses = require('./CheerleaderJSON/responses.json'); // responses generated by chatGPT https://chat.openai.com/share/229c7b62-eda9-48f0-9b1b-a5228f70dc08

/**
 * Function for generation a random number from 0 to a given limit
 * @param {number} upperLimit - number to be used as a maximum amount when a random number is being generated
 * @returns {number} - a randomly generated number between 0 and upperlimit
 */
function RNG(upperLimit) {
  return Math.floor(Math.random() * (upperLimit - 0 + 1) + 0);
}

/**
 * Creates a toast with displaying the given message
 * @param {string} message - a string containing what will be displayed in the toast
 */
const toast = (message) => {
  ToastAndroid.show(message, ToastAndroid.LONG);
};

/**
 * Called when a task is completed and will display a different toast message if is the last of the day
 * @param {Array} tasks - an array containing all tasks
 * @returns
 */
export function taskDoneToast(tasks) {
  const remainingTasks = [];
  for (let i = 0; i < tasks.length; i++) {
    if (tasks[i].done == 0) {
      remainingTasks.push(tasks[i]);
    }
  }
  if (remainingTasks.length - 1 == 0) {
    const length = responses.congratulations_messages_tasks_done.length;
    toast(responses.congratulations_messages_tasks_done[RNG(length)]);
  } else {
    const length = responses.congratulations_messages.length;
    toast(responses.congratulations_messages[RNG(length)]);
  }
}

/**
 * A tosts to be called when the user opens the app
 */
export function welcomeToast() {
  const length = responses.welcome_messages.length;
  toast(responses.welcome_messages[RNG(length)]);
}
