import { ToastAndroid } from 'react-native';
const responses = require('./CheerleaderJSON/responses.json'); // responses generated by chatGPT

// for returning a tone based message based on how much work the user has done

export function calculateTone(tasksDone, totalTasks) {
  const percentage = (tasksDone / totalTasks) * 100;

  if (percentage == 100) {
    console.log('cheerleader tone: amazed');
    return 'amazed';
  }
  if (percentage < 100) {
    if (percentage < 60) {
      if (percentage < 50) {
        console.log('cheerleader tone: disapointment');
        return 'disapointment';
      }
      console.log('cheerleader tone: conent');
      return 'content';
    }
    console.log('cheerleader tone: happy');
    return 'happy';
  }
}

function RNG(upperLimit) {
  return Math.floor(Math.random() * (upperLimit - 0 + 1) + 0);
}

const toast = (message) => {
  ToastAndroid.show(message, ToastAndroid.LONG);
};

export function taskDoneToast(tasks) {
  const remainingTasks = [];
  console.log(tasks);
  for (let i = 0; i < tasks.length; i++) {
    if (tasks[i].done == 0) {
      remainingTasks.push(tasks[i]);
    }
  }
  console.log(remainingTasks.length);
  if (remainingTasks.length - 1 == 0) {
    const length = responses.congratulations_messages_tasks_done.length;
    return toast(responses.congratulations_messages_tasks_done[RNG(length)]);
  } else {
    const length = responses.congratulations_messages.length;
    return toast(responses.congratulations_messages[RNG(length)]);
  }
}

export function welcomeToast() {
  const length = responses.welcome_messages.length;
  return toast(responses.welcome_messages[RNG(length)]);
}
